const inventory = [
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 1,
        "COVER": "SUPER MARIO WORLD",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 2,
        "COVER": "SUPER MARIO BROS. 3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 3,
        "COVER": "BART - LOS SIMPSONS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 1,
        "YEAR DATE": 1992,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 4,
        "COVER": "F-ZERO",
        "OWNED": "NO",
        "POSTER THEME": "DOUBLE DRAGON III"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 5,
        "COVER": "TINY TOONS",
        "OWNED": "NO",
        "POSTER THEME": "EXTRA: CUBITIPS SUPER MARIO BROS. 3"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 6,
        "COVER": "THE FLINSTONES - PICAPIEDRAS",
        "OWNED": "NO",
        "POSTER THEME": "EXTRA: CUBITIPS BATMAN RETURN OF THE JOKER"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 7,
        "COVER": "STREET FIGHTER II",
        "OWNED": "NO",
        "POSTER THEME": "STREET FIGHTER II / EXTRA: CUBITIPS SUPER MARIO WORLD"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 8,
        "COVER": "MARIO PAINT",
        "OWNED": "NO",
        "POSTER THEME": "FELIX THE CAT / AXELAY"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 9,
        "COVER": "DEATH VALLEY RALLY - COYOTE - CORRECAMINOS",
        "OWNED": "NO",
        "POSTER THEME": "CONTRA / SUPER MARIO KART"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 10,
        "COVER": "STARFOX",
        "OWNED": "NO",
        "POSTER THEME": "TMNT TURTLES IN TIME"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 11,
        "COVER": "BATMAN",
        "OWNED": "NO",
        "POSTER THEME": "ADVENTURE ISLAND 3"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 12,
        "COVER": "TINY TOONS",
        "OWNED": "NO",
        "POSTER THEME": "BATMAN RETURNS / CONTRA III"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 13,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 14,
        "COVER": "MORTAL KOMBAT",
        "OWNED": "NO",
        "POSTER THEME": "CYBERNATOR"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 15,
        "COVER": "STREET FIGHTER II TURBO",
        "OWNED": "NO",
        "POSTER THEME": "CALENDARIO 1994 / STARFOX"
    },
        {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "S.O.S. - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 2,
        "YEAR DATE": 1993,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 16,
        "COVER": "BATTLETOADS",
        "OWNED": "NO",
        "POSTER THEME": "RUN SABER"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 17,
        "COVER": "FINAL FIGHT 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 18,
        "COVER": "MEGAMAN X",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 19,
        "COVER": "METROID",
        "OWNED": "NO",
        "POSTER THEME": "MEGAMAN X"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 20,
        "COVER": "NBA JAM",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 21,
        "COVER": "JURASSIC PARK",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 22,
        "COVER": "MEGA MAN SOCCER",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 23,
        "COVER": "STUNT RACE FX",
        "OWNED": "NO",
        "POSTER THEME": "STREET FIGHTER II TURBO / KING OF FIGHTERS"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 24,
        "COVER": "SUPER METROID",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "SPEEDY GONZALES LOS GATOS BANDIDOS / SUPER METROID",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 25,
        "COVER": "ALIEN VS. PREDATOR - STUNT RACE FX - ITCHY & SCRATCHY",
        "OWNED": "NO",
        "POSTER THEME": "ALIEN VS. PREDATOR - STUNT RACE FX - ITCHY & SCRATCHY"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 26,
        "COVER": "SUPER BOMBERMAN 2 - SUPER ADVENTURE ISLAND 2 - DONKEY KONG COUNTRY",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "SUPER BOMBERMAN 2 - SUPER ADVENTURE ISLAND 2 - DONKEY KONG COUNTRY / LETHAL ENFORCERS",
        "OBSERVATION": "PÁGINA CENTRAL SUELTA",
        "COUNTRY": "ARGENTINA"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 27,
        "COVER": "DONKEY KONG COUNTRY",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 31-34",
        "POSTER THEME": "DONKEY KONG COUNTRY / DARKSTALKERS",
        "COUNTRY": "ARGENTINA"
    },
    {
        "YEAR EDIT": 3,
        "YEAR DATE": 1994,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 28,
        "COVER": "MORTAL KOMBAT II",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "CALENDARIO 1995",
        "COUNTRY": "ARGENTINA"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 29,
        "COVER": "DONKEY KONG COUNTRY",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 29-37",
        "POSTER THEME": "MORTAL KOMBAT II / MAXIMUM CARNAGE",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 30,
        "COVER": "KILLER INSTINCT",
        "OWNED": "NO",
        "POSTER THEME": "AERO THE ACRO-BAT 2 / X-MEN MUTAN APOCALYPSE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 31,
        "COVER": "FATAL FURY - CRESTA AMARILLA",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 31-34",
        "POSTER THEME": "FATAL FURY",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 32,
        "COVER": "SPIDER MAN",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "FX FIGHTER / SPIDER-MAN",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 33,
        "COVER": "MEGAMAN X2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 34,
        "COVER": "CLAYFIGHTER 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 35,
        "COVER": "KILLER INSTINCT",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 36,
        "COVER": "POWER RANGERS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 37,
        "COVER": "VIRTUAL BOY",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 38,
        "COVER": "YOSHI'S ISLAND - BEBÉ MARIO",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINA CENTRAL SUELTA",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 39,
        "COVER": "MORTAL KOMBAT 3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 4,
        "YEAR DATE": 1995,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 40,
        "COVER": "DIDDY KONG'S QUEST",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 41,
        "COVER": "MARIO - NINTENDO 64 - ULTRA 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 42,
        "COVER": "SUPER MARIO RPG",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 43,
        "COVER": "DRAGON BALL",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 44,
        "COVER": "KILLER INSTINCT 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 45,
        "COVER": "TOY STORY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 46,
        "COVER": "STREET FIGHTER ZERO 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 47,
        "COVER": "SUPER MARIO 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "JULIO",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "SUPER MARIO 64 - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 48,
        "COVER": "KEN GRIIFEY JR'S WINNING RUN",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 49,
        "COVER": "NINTENDO 64 - PILOTWINGS 64",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 50,
        "COVER": "STAR WARS SHADOWS OF THE EMPIRE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 51,
        "COVER": "MORTAL KOMBAT TRILOGY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 5,
        "YEAR DATE": 1996,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 52,
        "COVER": "KILLER INSTINCT GOLD",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 53,
        "COVER": "MARIO KART 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 54,
        "COVER": "TUROK",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 55,
        "COVER": "THE KING OF FIGHTERS 95",
        "OWNED": "NO",
        "POSTER THEME": "PILOTWINGS 64 / ULTIMATE MK3 - MK TRILOGY"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 56,
        "COVER": "MARIO - LUIGI - PEACH - BOWSER",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 57,
        "COVER": "BLAST CORPS",
        "OWNED": "NO",
        "POSTER THEME": "STREET FIGHTER ALPHA 2 / KIRBY STAR STACKER"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 58,
        "COVER": "STARFOX 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 59,
        "COVER": "CLAYFIGHTER 63 1/3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 60,
        "COVER": "BANJO - KAZOOIE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 61,
        "COVER": "GOLDENEYE 007",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 62,
        "COVER": "SAN FRANCISCO RUSH EXTREME RACING",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 63,
        "COVER": "DIDDY KONG RACING",
        "OWNED": "NO",
        "POSTER THEME": "GOLDENEYE 007 / MARIO KART 64"
    },
    {
        "YEAR EDIT": 6,
        "YEAR DATE": 1997,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 64,
        "COVER": "BOMBERMAN 64",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 65,
        "COVER": "ZELDA OCARINE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 66,
        "COVER": "YOSHI'S STORY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 67,
        "COVER": "NINJA GOEMON",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 68,
        "COVER": "1080 SNOWBOARDING",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINAS 1-2 FALTA PEDAZO",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 69,
        "COVER": "WORLD CUP 98",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 70,
        "COVER": "BANJO - KAZOOIE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 71,
        "COVER": "MORTAL KOMBAT 4",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
        {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "JULIO",
        "YEAR NUMBER": "SPECIAL",
        "OVERALL NUMBER": "SPECIAL",
        "COVER": "ENCICLOPEDIA - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 72,
        "COVER": "F-1 WORLD GRAND PRIX",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 73,
        "COVER": "POKEMON STAR PIKACHU - CRUIS'N WORLD",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 74,
        "COVER": "POKEMON - ASH - PIKACHU",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 75,
        "COVER": "ZELDA OCARINA",
        "OWNED": "NO",
        "POSTER THEME": "THE LEGEND OF ZELDA: OCARINA OF TIME"
    },
    {
        "YEAR EDIT": 7,
        "YEAR DATE": 1998,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 76,
        "COVER": "TUROK 2",
        "OWNED": "NO",
        "POSTER THEME": "YOSHI'S STORY"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 77,
        "COVER": "CASTLEVANIA",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "DEADLY ARTS / POKEMON",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 78,
        "COVER": "MARIO PARTY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 79,
        "COVER": "NBA INTHE ZONE 99",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 80,
        "COVER": "SUPER SMASH BROTHERS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 81,
        "COVER": "RAYMAN 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 82,
        "COVER": "STAR WARS RACER",
        "OWNED": "NO",
        "POSTER THEME": "STAR WARS RACER"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 83,
        "COVER": "SHADOW MAN",
        "OWNED": "NO",
        "POSTER THEME": "SHADOW MAN"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 84,
        "COVER": "POKEMON SNAP",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 29-36",
        "POSTER THEME": "POKEMON SNAP",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 85,
        "COVER": "HYBRID HEAVEN",
        "OWNED": "NO",
        "POSTER THEME": "HYBRID HEAVEN",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 86,
        "COVER": "JETFORCE GEMINI",
        "OWNED": "NO",
        "POSTER THEME": "JETFORCE GEMINI"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 87,
        "COVER": "STARCRAFT 64",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "RE-VOLT",
        "OBSERVATION": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 8,
        "YEAR DATE": 1999,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 88,
        "COVER": "DONKEY KONG 64",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁG. 7 RECORTADA",
        "COUNTRY": "VENEZUELA"
    },
     {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 89,
        "COVER": "MARIO PARTY 2",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "DONKEY KONG 64 / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 90,
        "COVER": "RR64",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 91,
        "COVER": "POKEMON STADIUM",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "100 PORTADAS / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 92,
        "COVER": "POKEMON TRADING CARD GAME",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 93,
        "COVER": "PERFECT DARK",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "POKEMON STADIUM (CALENDARIO MAYO-JUNIO) / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 94,
        "COVER": "EXCITEBIKE 64",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 95,
        "COVER": "KIRBY 64",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "PERFECT DARK / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 96,
        "COVER": "TUROK 3",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 97,
        "COVER": "MARIO TENNIS - PEACH - DAISY",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "BATMAN BEYOND / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 98,
        "COVER": "POKEMON",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 99,
        "COVER": "ZELDA MAJORA'S",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "THE LEGEND OF ZELDA: MAJORA'S MASK / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 9,
        "YEAR DATE": 2000,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 100,
        "COVER": "BANJO-TOOIE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 101,
        "COVER": "PAPER MARIO",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "TUROK 3 / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 102,
        "COVER": "MEGA MAN 64",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 103,
        "COVER": "POKEMON STADIUM 2",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "PAPER MARIO / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 104,
        "COVER": "KIRBY",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 105,
        "COVER": "MARIO PARTY 3",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "CONKER'S BAD FUR DAY / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 106,
        "COVER": "GAMEBOY ADVANCE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 107,
        "COVER": "CASTLEVANIA",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "THE LEGEND OF ZELDA: ORACLE OF AGES-SEASONS / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 108,
        "COVER": "MARIO KART SUPER CIRCUIT",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 109,
        "COVER": "SUPER STREET FIGHTER II",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "SUPER STREET FIGHTER II / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 110,
        "COVER": "GAMECUBE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 111,
        "COVER": "LUIGI'S MANSION",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "GAMECUBE / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 10,
        "YEAR DATE": 2001,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 112,
        "COVER": "10 AÑOS - SUPER SMAH BROS. MELEE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 113,
        "COVER": "ETERNAL DARKNESS",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "ETERNAL DARKNESS / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 114,
        "COVER": "NBA COURTSIDE2002 - KOBE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 115,
        "COVER": "SUPER MARIO WORLD - YOSHI - SUPER MARIO ADVANCE 2",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "MEGAMAN BATTLE NETWORK 2 / ARTE SOBRES",
        "OBSERVATION": "PÁGINAS RECORTADAS: 9-10, 95-96",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 116,
        "COVER": "SONIC ADVENTURE 2 BATTLE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PÁGINA 94 MEDIO SUELTA",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 117,
        "COVER": "RESIDENT EVIL",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "SONIC ADVENTURE 2 BATTLE / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 118,
        "COVER": "2002 FIFA WORLD CUP",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 119,
        "COVER": "E3 - SUPER MARIO SUNSHINE - ZELDA - METROID - STARFOX",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 120,
        "COVER": "SUPER MARIO SUNSHINE",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 121,
        "COVER": "STARFOX ADVENTURES",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "MEGAMAN BATTLE NETWORK 2 / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 122,
        "COVER": "MARIO PARTY 4",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "CONTRAPORTADA UN POCO ROTA",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 123,
        "COVER": "METROID PRIME",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "MARIO PARY 4 / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 11,
        "YEAR DATE": 2002,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 124,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 125,
        "COVER": "POKEMON",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 126,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 127,
        "COVER": "POKEMON",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "KIRBY NIGHTMARE IN DREAM LAND / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 128,
        "COVER": "GOLDEN SUN",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 129,
        "COVER": "WARIO WORLD",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "THE LEGEND OF ZELDA: THE WIND WAKER / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 130,
        "COVER": "ADVANCE WARS 2",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 131,
        "COVER": "F-ZERO GX",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 132,
        "COVER": "ZELDA - SOUL CALIBUR II",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 133,
        "COVER": "VIEWTIFUL JOE",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "SOUL CALIBUR II / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 134,
        "COVER": "STAR WARS",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "VIEWTIFUL JOE / P.N.03",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 135,
        "COVER": "MARIO KART DOUBLE DASH",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "FINAL FANTASY TACTICS ADVANCE / MARIO KART DOUBLE DASH",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 12,
        "YEAR DATE": 2003,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 136,
        "COVER": "MARIO & LUIGI",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 137,
        "COVER": "FINAL FANTASY",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "FIRE EMBLEM / SOUL OF MANA",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 138,
        "COVER": "METAL GEAR SOLID",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 139,
        "COVER": "POKEMON COLLOSEUM",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "FINAL FANTASY CRYSTAL CHRONICLES / METAL GEAR SOLID THE TWIN SNAKES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 140,
        "COVER": "BOMBERMAN JETTERS",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 141,
        "COVER": "HARRY POTTER AZKABAN",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "THE LORD OF THE RINGS: THE RETURN OF THE KING",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 142,
        "COVER": "TALES OF SIMPHONIA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 143,
        "COVER": "E3 - ZELDA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 144,
        "COVER": "DONKEY KONGA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 145,
        "COVER": "SRS - STREET RACING SYNDICATE",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "KIRBY & THE AMAZING MIRROR / SRS",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 146,
        "COVER": "METROID PRIME 2 ECHOES",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 147,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 33-48",
        "POSTER THEME": "PRINCE OF PERSIA WARRIOR WITHIN",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 13,
        "YEAR DATE": 2004,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 148,
        "COVER": "NINTENDO DS - ANIVERSARIO XIII",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 149,
        "COVER": "RESIDENT EVIL 4",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 73-88",
        "POSTER THEME": "RESIDENT EVIL 4",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 150,
        "COVER": "MORTAL KOMBAT DECEPTION",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 151,
        "COVER": "SPLINTER CELL",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "SPLINTER CELL / THE LEGEND OF ZELDA: THE MINISH CAP",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 152,
        "COVER": "GAMECUBE - NINTENDO DS - GAMEBOY ADVANCE - REVOLUTION",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 153,
        "COVER": "STAR WARS EPISODE III",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "POKEMON EMERALD VERSION / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 154,
        "COVER": "KILLER 7",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 155,
        "COVER": "E3 - ZELDA - MIYAMOTO",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 156,
        "COVER": "GEIST",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "GEIST / YOSHI TOPSY-TURVY",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 157,
        "COVER": "MARIO SUPERSTAR BASEBALL",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "MEGAMAN BATTLE NETWORK 5 / ARTE SOBRES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 158,
        "COVER": "MARIO KART DS",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 159,
        "COVER": "SUPER MARIO STRIKERS",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "RAINBOW SIX / CASTLEVANIA: DAWN OF SORROW",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 14,
        "YEAR DATE": 2005,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 160,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 73-88",
        "POSTER THEME": "MARIO STRIKERS",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
     {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 161,
        "COVER": "ESTRELLAS DEL 2006 - MARIO - LUIGI - KIRBY - METROID - PEACH - ZELDA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 162,
        "COVER": "SUPER PRINCESS PEACH",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "X-MEN LEGENDS II / PRINCE OF PERSIA THE TWO THRONES",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 163,
        "COVER": "METROID PRIME HUNTERS",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "METROID PRIME HUNTERS / CHIBI-ROBO",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 164,
        "COVER": "NARUTO CLASH OF NINJA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 165,
        "COVER": "NEW SUPER MARIO BROS.",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 41-48",
        "POSTER THEME": "MARIO Y LUIGI",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 166,
        "COVER": "WII",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 167,
        "COVER": "E3 - REDSTEEL",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 168,
        "COVER": "STARFOX COMMAND",
        "OWNED": "NO",
        "POSTER": "MISSING: PAGES 41-48",
        "POSTER THEME": "SUPER MONKEY BALL ADVENTURE / CASTLEVANIA PORTRAIT OF RUIN",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 169,
        "COVER": "MARIO VS. DONKEY KONG 2",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 170,
        "COVER": "FIFA 07",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 171,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 73-88",
        "POSTER THEME": "THE LEGEND OF ZELDA TWILIGHT PRINCESS",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 15,
        "YEAR DATE": 2006,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 172,
        "COVER": "XV AÑOS",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 57-64",
        "POSTER THEME": "REDSTEEL / MARVEL ULTIMATE ALLIANCE",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
     {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 173,
        "COVER": "WARIOWARE SMOOTH MOVES",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 174,
        "COVER": "DIDDY KONG RACING DS",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 57-64",
        "POSTER THEME": "DIDDY KONG RACING DS / THE LEGEND OF ZELDA TWILIGHT PRINCESS",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 175,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 176,
        "COVER": "TMNT - TEENAGE MUTANT NINJA TURTLES",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 57-64",
        "POSTER THEME": "PRINCE OF PERSIA RIVAL SWORDS / LUNAR KNIGHTS",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 177,
        "COVER": "SPIDER MAN 3",
        "OWNED": "NO",
        "POSTER": "INCLUDED: PAGES 57-64",
        "POSTER THEME": "TMNT / SPIDER-MAN 3 THE GAME",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 178,
        "COVER": "HARRY POTTER PHOENIX",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 179,
        "COVER": "MARIO STRIKERS CHARGED",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 180,
        "COVER": "METROID PRIME 3 CORRUPTION",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 181,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 182,
        "COVER": "FIFA 08",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 183,
        "COVER": "SUPER MARIO GALAXY",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 16,
        "YEAR DATE": 2007,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 184,
        "COVER": "MARIO PARTY DS",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 185,
        "COVER": "2008 - MARIO KART WII",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 186,
        "COVER": "SUPER SMASH BROS. BRAWL",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 187,
        "COVER": "NO MORE HEROES",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 188,
        "COVER": "OKAMI",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 189,
        "COVER": "MARIO KART WII",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 190,
        "COVER": "GUITAR HERO",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 191,
        "COVER": 200,
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 192,
        "COVER": "FINAL FANTASY IV",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 193,
        "COVER": "E3 - WARIO",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 194,
        "COVER": "HARRY POTTER",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 195,
        "COVER": "RAYMAN RAVING RABBIDS",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 17,
        "YEAR DATE": 2008,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 196,
        "COVER": "ANIMAL CROSSING",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
     {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 197,
        "COVER": "PRINCE OF PERSIA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 198,
        "COVER": "MEGA MAN",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 199,
        "COVER": "DEADRISING - ZOMBIS",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 200,
        "COVER": "POKEMON PLATINUM",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 201,
        "COVER": "PUNCH OUT WII",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 202,
        "COVER": "NEED FOR SPEED NITRO",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 203,
        "COVER": "E3 - ZELDA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 204,
        "COVER": "MARIO - YOSHI - MÁS DE 60",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 205,
        "COVER": "METROID PRIME TRILOGY",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 206,
        "COVER": "PES 2010 - MESSI",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 207,
        "COVER": "TATSUNOKO VS. CAPCOM - RYU - CHUN LI",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 18,
        "YEAR DATE": 2009,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 208,
        "COVER": "TENEMOS ESTRELLA - MARIO",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
      {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 209,
        "COVER": "NO MORE HEROES 2",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        "COUNTRY": "VENEZUELA"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 210,
        "COVER": "SONIC",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 211,
        "COVER": "WARIOWARE D.I.Y.",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 212,
        "COVER": "SUPER MARIO GALAXY 2 - YOSHI",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 213,
        "COVER": "IRON MAN 2",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 214,
        "COVER": "E3 - MARIO - LUIGI - BASKETBALL",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 215,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 216,
        "COVER": "METROID OTHER M",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 217,
        "COVER": "NBA JAM",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 218,
        "COVER": "PES 2011 - MESSI",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 19,
        "YEAR DATE": 2010,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 219,
        "COVER": "DONKEY KONG COUNTRY RETURNS",
        "OWNED": "NO",
        "POSTER": "MISSING: CHILEAN VERSION",
        "POSTER THEME": "METROID OTHER M / DONKEY KONG COUNTRY RETURN",
        "OBSERVATION": "DAÑO EN EL LOMO",
        
    },
     {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 220,
        "COVER": "25TH ANNIVERSARY - SUPER MARIO ALL STARS",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 221,
        "COVER": "CONDUIT 2",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PEQUEÑO HUECO EN LA PORTADA. PÁG 83-84 UN POCO ROTA",
        
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 222,
        "COVER": "KID ICARUS - NINTENDO 3DS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 223,
        "COVER": "SUPER STREET FIGHTER IV 3D EDITION",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 224,
        "COVER": "SONIC",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 225,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 226,
        "COVER": "E3 - MARIO - WII U",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 227,
        "COVER": "METAL GEAR SOLID 3D",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 228,
        "COVER": "STARFOX 64 3D",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 229,
        "COVER": "FIFA 12 - ROONEY - MARQUEZ",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 230,
        "COVER": "MARIO & SONIC AT THE LONDON 2012 OLYMPIC GAMES",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 20,
        "YEAR DATE": 2011,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 231,
        "COVER": "ZELDA",
        "OWNED": "NO",
        "POSTER THEME": "THE LEGEND OF ZELDA: SKYWARD SWORD"
    },
     {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 232,
        "COVER": "SUPER MARIO 3D LAND",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 233,
        "COVER": "TEKKEN 3D PRIME EDITION",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 234,
        "COVER": "KID ICARUS",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 235,
        "COVER": "BEBÉ MARIO - POKEPARK 2",
        "OWNED": "NO",
        "POSTER": "MISSING: CHILEAN VERSION",
        "POSTER THEME": "MARIO KART 7 / POKEPARK 2",
        "OBSERVATION": "FROM CHILE",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 236,
        "COVER": "EPIC MICKEY 2",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 237,
        "COVER": "MARIO TENNIS OPEN",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PORTADA DAÑADA EN ESQUINA SUPERIOR DERECHA. CONTRAPORTADA CON TROZO FALTANTE",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 238,
        "COVER": "NEW SUPER MARIO BROS. U",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "MISSING PAGES: 19-20",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 239,
        "COVER": "RAYMAN",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 240,
        "COVER": "METROID",
        "OWNED": "NO",
        "POSTER THEME": "METROID"
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 241,
        "COVER": "KIRBY 20TH ANNIVERSARY - CELEBREMOS",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "PORTADA Y PÁG 1-2 ARRUGADAS. PÁG 1-2 FALTA PEDAZO",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 242,
        "COVER": "NINTENDO LAND - WII U",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
        
    },
    {
        "YEAR EDIT": 21,
        "YEAR DATE": 2012,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 243,
        "COVER": "21 ANIVERSARIO - MARIO - YOSHI",
        "OWNED": "NO",
        "POSTER THEME": "NEW SUPER MARIO BROS. U / BATMAN ARKHAM CITY"
    },
     {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 244,
        "COVER": "NINJA GAIDEN 3",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 245,
        "COVER": "LUIGI'S MANSION",
        "OWNED": "NO",
        "POSTER": "-",
        "POSTER THEME": "-",
        "OBSERVATION": "-",
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 246,
        "COVER": "CASTLEVANIA",
        "OWNED": "NO",
        "POSTER THEME": "CASTLEVANIA: LORD OF SHADOW / LUIGI'S MANSION DARK MOON"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 247,
        "COVER": "INJUSTICE",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 248,
        "COVER": "DONKEY KONG",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 249,
        "COVER": "ANIMAL CROSSING",
        "OWNED": "NO",
        "POSTER THEME": "CALENDARIOS DE ANIMAL CROSSING (JUN 2013 - MAYO 2014)"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 250,
        "COVER": "DISNEY INFINITY",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 251,
        "COVER": "SUPER SMASH BROS.",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 252,
        "COVER": "PIKMIN 3",
        "OWNED": "NO",
        "POSTER THEME": "SUPER SMASH BROS. (3DS - WII U) / NEW SUPER LUIGI U",
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 253,
        "COVER": "ZELDA WINDWAKER HD",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 254,
        "COVER": "SONIC LOST WORLD",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 22,
        "YEAR DATE": 2013,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 255,
        "COVER": "SUPER MARIO 3D WORLD",
        "OWNED": "NO",
        "POSTER THEME": "SUPER MARIO 3D WORLD / THE LEGEND OF ZELDA: A LINK BETWEEN WORLDS",
    },
     {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 256,
        "COVER": "MARIO PARTY ISLAND TOUR",
        "OWNED": "NO",
        "POSTER THEME": "-"
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 257,
        "COVER": "ZELDA - PAREJAS LEGENDARIAS",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 258,
        "COVER": "DONKEY KONG COUNTRY TROPICAL FREEZE",
        "OWNED": "NO",
        "POSTER THEME": "DONKEY KONG COUNTRY TROPICAL FREEZE / MARIO PARTY ISLAND TOUR",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 259,
        "COVER": "YOSHI'S NEW ISLAND - BEBÉ MARIO",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 260,
        "COVER": "MARIO KART 8",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 261,
        "COVER": "KIRBY TRIPLE DELUXE",
        "OWNED": "NO",
        "POSTER THEME": "MARIO KART 8 / YOSHI'S NEW ISLAND",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 262,
        "COVER": "SUPER SMASH BROS. FOR NINTENDO 3DS",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 263,
        "COVER": "DISNEY INFINITY 2.0 - SPIDER MAN",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 264,
        "COVER": "ZELDA - HYRULE WARRIORS",
        "OWNED": "NO",
        "POSTER THEME": "MARIO GOLF WORLD TOUR - HYRULE WARRIORS",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 265,
        "COVER": "BAYONETTA 2",
        "OWNED": "NO",
        "POSTER THEME": "-",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 266,
        "COVER": "EL MUNDO DE BOWSER - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "MARIO PARTY 10 / MARIO & LUIGI BOWSER'S INSIDE STORY",
    },
    {
        "YEAR EDIT": 23,
        "YEAR DATE": 2014,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 267,
        "COVER": "SUPER SMASH BROS. FOR WII U",
        "OWNED": "NO",
        "POSTER THEME": "BAYONETTA 2 / SUPER SMASH BROS. FOR WII U",
    },
     {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 268,
        "COVER": "LA JUNGLA DE DONKEY KONG - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "MARZO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 269,
        "COVER": "EL MUNDO DE SUPER MARIO - SPECIAL",
        "OWNED": "NO",
        "POSTER THEME": "-",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 270,
        "COVER": "ZELDA MAJORA'S MASK",
        "OWNED": "NO",
        "POSTER THEME": "THE LEGEND OF ZELDA: MAJORA'S MASK 3D",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "MAYO",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 271,
        "COVER": "MARIO VS. DONKEY KONG TIPPING STARS",
        "OWNED": "NO",
        "POSTER THEME": "KIRBY AND THE RAINBOW CURSE - XENOBLADE CHRONICLES 3D",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 272,
        "COVER": "MARIO PARTY 10",
        "OWNED": "NO",
        "POSTER THEME": "MARIO PARTY 10 - MONSTER HUNTER 4 ULTIMATE",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "JULIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 273,
        "COVER": "SPLATOON",
        "OWNED": "NO",
        "POSTER THEME": "SPLATOON / CODE NAME: S.T.E.AM",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 274,
        "COVER": "SUPER MARIO MAKER",
        "OWNED": "NO",
        "POSTER THEME": "SUPER MARIO MAKER / SUPER MARIO BROS.",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 275,
        "COVER": "YOSHI'S WOOLY WORLD",
        "OWNED": "NO",
        "POSTER THEME": "YOSHI'S WOOLY WORLD - ZELDA",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 276,
        "COVER": "ZELDA TRIFORCE HEROES",
        "OWNED": "NO",
        "POSTER THEME": "THE LEGEND OF ZELDA TRIFORCE HEORES / ANIMAL CROSSING HAPPY HOME DESIGNER",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 277,
        "COVER": "MARIO TENNIS ULTRA SMASH",
        "OWNED": "NO",
        "POSTER THEME": "MARIO TENNIS ULTRA SMASH / FATAL FRAME MAIDEN OF BLACK WATER",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 24,
        "YEAR DATE": 2015,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 278,
        "COVER": "MARIO DORADO FONDO ROJO EDICIÓN ANIVERSARIO",
        "OWNED": "NO",
        "POSTER THEME": "AMIIBO / AMIIBO SUPER SMASH BROS. 3DS Y WII U",
        "COUNTRY": "CHILE"
    },
     {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 279,
        "COVER": "MARIO & LUIGI PAPER JAM",
        "OWNED": "NO",
        "POSTER THEME": "MEGA MAN LEGACY COLLECTION / XENOBLADE CHRONICLES X",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 280,
        "COVER": "SUPER SMASH BROS. FOR NINTENDO 3DS / FOR WII U - BAYONETTA",
        "OWNED": "NO",
        "POSTER THEME": "SUPER SMASH BROS / MIGHTY Nº 9",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 281,
        "COVER": "HYRULE WARRIORS LEGENDS",
        "OWNED": "NO",
        "POSTER THEME": "HYRULE WARRIORS LEGENDS / SUPER SMASH BROS. 3DS WIIU",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 282,
        "COVER": "METROID PRIME FEDERATION FORCE",
        "OWNED": "NO",
        "POSTER THEME": "METORID FEDERATION FORCE / THE LEGEND PF ZELDA THE TWILIGHT PRINCESS HD",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 283,
        "COVER": "STAR FOX ZERO",
        "OWNED": "NO",
        "POSTER THEME": "STAR FOX ZERO / BRAVELY SECOND END LAYER",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 284,
        "COVER": "KIRBY PLANET ROBOBOT",
        "OWNED": "NO",
        "POSTER THEME": "KIRBY PLANET ROBOBOT / STAR FOX ZERO",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 285,
        "COVER": "THE LEGEND OF ZELDA BREATH OF THE WILD",
        "OWNED": "NO",
        "POSTER THEME": "THE LEGEND OF ZELDA BREATH OF THE WILD / TOKYO MIRAGE SESSIONS #FE",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 286,
        "COVER": "METROID 30 AÑOS",
        "OWNED": "NO",
        "POSTER THEME": " METROID PRIME 2: ECHOES / METROID PRIME 3: CORRUPTION",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 287,
        "COVER": "YO-KAI WATCH 2 BONY SPIRITS",
        "OWNED": "NO",
        "POSTER THEME": "YO-KAI WATCH 2 / MONSTER HUNTER GENERATIONS",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 288,
        "COVER": "POKEMON GO",
        "OWNED": "NO",
        "POSTER THEME": "POKEMON GO",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 289,
        "COVER": "NES CLASSIC EDITION",
        "OWNED": "NO",
        "POSTER THEME": "MARIO PARTY STAR RUSH / POKEMON SUN - MOON",
        "COUNTRY": "CHILE"
    },
    {
        "YEAR EDIT": 25,
        "YEAR DATE": 2016,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 290,
        "COVER": "SUPER MARIO MAKER FOR NINTENDO 3DS",
        "OWNED": "NO",
        "POSTER THEME": "SUPER MARIO MAKER 3DS / POKEMON SUN - MOON",
        "COUNTRY": "CHILE"
    },
     {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 291,
        "COVER": "YOSHI'S WOOLLY WORLD - SUPER MARIO RUN",
        "OWNED": "NO",
        "POSTER THEME": "YOSHI'S WOOLLY WORLD - SUPER MARIO MAKER FOR NINTENDO 3DS",
        
    },
    {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 292,
        "COVER": "MARIO SPORTS SUPERSTARS",
        "OWNED": "NO",
        "POSTER THEME": "MARIO SPORTS SUPERSTARS - SUPER MARIO MAKER FOR NINTENDO 3DS",
        
    },
     {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 293,
        "COVER": "ZELDA BREATH OF THE WILD",
        "OWNED": "NO",
        "POSTER THEME": "ZELDA BREATH OF THE WILD",
        
    },
    {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 294,
        "COVER": "MARIO KART 8 DELUXE",
        "OWNED": "NO",
        "POSTER THEME": "MARIO KART 8 DELUXE",
        
    },
     {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 295,
        "COVER": "ULTRA STREET FIGHTER II THE FINAL CHALLENGERS",
        "OWNED": "NO",
        "POSTER THEME": "ULTRA STREET FIGHTER II THE FINAL CHALLENGERS - ARMS",
        
    },
    {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 296,
        "COVER": "SPLATOON 2",
        "OWNED": "NO",
        "POSTER THEME": "SPLATOON 2 - ULTRA STREET FIGHTER II THE FINAL CHALLENGERS",
        
    },
      {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 297,
        "COVER": "SUPER MARIO ODYSSEY - E3 2017",
        "OWNED": "NO",
        "POSTER THEME": "SUPER MARIO ODYSSEY - ARMS",
        
    },
    {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 298,
        "COVER": "MARIO + RABBIDS: KINGDOM BATTLE",
        "OWNED": "NO",
        "POSTER THEME": "MARIO + RABBIDS: KINGDOM BATTLE - THE LEGEND OF ZELDA BREATH OF THE WILD: THE MASTER TRIALS",
        
    },
     {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 299,
        "COVER": "POKKÉN TOURNAMENT DX",
        "OWNED": "NO",
        "POSTER THEME": "POKKÉN TOURNAMENT DX - METROID SAMUS RETURNS",
        
    },
    {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 300,
        "COVER": "MARIO & LUIGI SUPERSTAR SAGA + BOWSER'S MINIONS",
        "OWNED": "NO",
        "POSTER THEME": "MARIO & LUIGI SUPERSTAR SAGA + BOWSER'S MINIONS - FIRE EMBLEM WARRIORS",
        
    },
     {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 301,
        "COVER": "SUPER MARIO ODYSSEY",
        "OWNED": "NO",
        "POSTER THEME": "SUPER MARIO ODYSSEY (CALENDARIO NOV Y DIC) - MARIO PARTY THE TOP 100",
        
    },
    {
        "YEAR EDIT": 26,
        "YEAR DATE": 2017,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 302,
        "COVER": "XENOBLADE CHRONICLES 2",
        "OWNED": "NO",
        "POSTER THEME": "XENOBLADE CHRONICLES 2 - LAYTON'S MYSTERY JOURNEY",
        
    },
    {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 303,
        "COVER": "KIRBY BATTLE ROYALE",
        "OWNED": "NO",
        "POSTER THEME": "KIRBY BATTLE ROYALE - RESIDENT EVIL REVELATIONS COLLECTION",
        
    },
    {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 303,
        "COVER": "BAYONETTA 2",
        "OWNED": "NO",
        "POSTER THEME": "BAYONETTA 2 - DRAGON QUEST BUILDERS",
        
    },
     {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 304,
        "COVER": "KIRBY STAR ALLIES",
        "OWNED": "NO",
        "POSTER THEME": "KIRBY STAR ALLIES - DETECTIVE PIKACHU",
        
    },
    {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "ABRIL",
        "YEAR NUMBER": 4,
        "OVERALL NUMBER": 305,
        "COVER": "HYRULE WARRIORS: DEFINITIVE EDITION",
        "OWNED": "NO",
        "POSTER THEME": "HYRULE WARRIORS: DEFINITIVE EDITION",
        
    },
     {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "MAYO",
        "YEAR NUMBER": 5,
        "OVERALL NUMBER": 306,
        "COVER": "STREET FIGHTER 30TH ANNIVERSARY COLLECTION",
        "OWNED": "NO",
        "POSTER THEME": "STREET FIGHTER 30TH ANNIVERSARY COLLECTION - DARK SOULS REMASTERED",
        
    },
    {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "JUNIO",
        "YEAR NUMBER": 6,
        "OVERALL NUMBER": 307,
        "COVER": "MARIO TENNIS ACES",
        "OWNED": "NO",
        "POSTER THEME": "MARIO TENNIS ACES - CAPTAIN TOAD: TREASURE TRACKER",
        
    },
     {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "JULIO",
        "YEAR NUMBER": 7,
        "OVERALL NUMBER": 308,
        "COVER": "SUPER SMASH BROS. ULTIMATE",
        "OWNED": "NO",
        "POSTER THEME": "SUPER SMASH BROS. ULTIMATE - CRASH BANDICOOT N. SANE TRILOGY",
        
    },
    {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "AGOSTO",
        "YEAR NUMBER": 8,
        "OVERALL NUMBER": 309,
        "COVER": "STARLINK: BATTLE FOR ATLAS",
        "OWNED": "NO",
        "POSTER THEME": "SUPER SMASH BROS. ULTIMATE - MARIO + RABBIDS KINGDOM BATTLE: DONKEY KONG ADVENTURE",
        
    },
     {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "SEPTIEMBRE",
        "YEAR NUMBER": 9,
        "OVERALL NUMBER": 310,
        "COVER": "DRAGON BALL FIGHTERZ",
        "OWNED": "NO",
        "POSTER THEME": "SUPER SMASH BROS. ULTIMATE - WARIOWARE GOLD",
        
    },
    {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "OCTUBRE",
        "YEAR NUMBER": 10,
        "OVERALL NUMBER": 311,
        "COVER": "LUIGI'S MANSION",
        "OWNED": "NO",
        "POSTER THEME": "SUPER SMASH BROS. ULTIMATE - LUIGI'S MANSION",
        
    },
     {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "NOVIEMBRE",
        "YEAR NUMBER": 11,
        "OVERALL NUMBER": 312,
        "COVER": "POKÉMON: LET'S GO, PIKACHU! AND EEVEE!",
        "OWNED": "NO",
        "POSTER THEME": "SUPER SMASH BROS. ULTIMATE - THE LEGEND OF ZELDA: OCARINA OF TIME",
        
    },
    {
        "YEAR EDIT": 27,
        "YEAR DATE": 2018,
        "MONTH": "DICIEMBRE",
        "YEAR NUMBER": 12,
        "OVERALL NUMBER": 313,
        "COVER": "SUPER SMASH BROS.: ULTIMATE",
        "OWNED": "NO",
        "POSTER THEME": "CELESTE - CAPCOM BEAT'EM UP BUNDLE",
        
    },
      {
        "YEAR EDIT": 28,
        "YEAR DATE": 2019,
        "MONTH": "ENERO",
        "YEAR NUMBER": 1,
        "OVERALL NUMBER": 314,
        "COVER": "SUPER MARIO BROS. U DELUXE",
        "OWNED": "NO",
        "POSTER THEME": "SUPER MARIO BROS. U DELUXE - POKÉMON: LET'S GO, PIKACHU! AND EEVEE!",
        
    },
    {
        "YEAR EDIT": 28,
        "YEAR DATE": 2019,
        "MONTH": "FEBRERO",
        "YEAR NUMBER": 2,
        "OVERALL NUMBER": 315,
        "COVER": "KIRBY'S EXTRA EPIC YARN",
        "OWNED": "NO",
        "POSTER THEME": "KIRBY'S EXTRA EPIC YARN - MARIO & LUIGI: BOWSER'S INSIDE STORY + BOWSER JR.'S JOURNEY",
        
    },
     {
        "YEAR EDIT": 28,
        "YEAR DATE": 2019,
        "MONTH": "MARZO",
        "YEAR NUMBER": 3,
        "OVERALL NUMBER": 316,
        "COVER": "YOSHI'S CRAFTED WORLD",
        "OWNED": "NO",
        "POSTER THEME": "RESIDENT EVIL 2: 21 ANIVERSARIO - YOSHI'S CRAFTED WORLD",
        
    },
];

export default inventory;